var nome = "La\u00EDs";
var idade = 15;
var saudacao = "Bom dia!";
var tempo = "Ler";
var tempo1 = "Filmes";
var tempo2 = "Correr";
var formacao = "Gest\u00E3o de T.i";
var formacao2 = "Engenharia da Computa\u00E7\u00E3o";
console.log("".concat(saudacao));
console.log("Meu nome \u00E9 ".concat(nome, " Zanqueta, a minha idade \u00E9 ").concat(idade, " anos , tenho como momento de lazer ").concat(tempo, ", ver ").concat(tempo1, " \n    e o que eu mais gosto \u00E9 de ").concat(tempo2, ". Pretendo ingressar em uma universidade, at\u00E9 esse momento \n    estou tendenciosa a fazer ").concat(formacao, " minha segunda op\u00E7\u00E3o \u00E9 ").concat(formacao2));
